//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.5472
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalTestV8.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool gdDisable {
            get {
                return ((bool)(this["gdDisable"]));
            }
            set {
                this["gdDisable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool a2Disable {
            get {
                return ((bool)(this["a2Disable"]));
            }
            set {
                this["a2Disable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool a3Disable {
            get {
                return ((bool)(this["a3Disable"]));
            }
            set {
                this["a3Disable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool a4Disable {
            get {
                return ((bool)(this["a4Disable"]));
            }
            set {
                this["a4Disable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool b1Disable {
            get {
                return ((bool)(this["b1Disable"]));
            }
            set {
                this["b1Disable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool b2Disable {
            get {
                return ((bool)(this["b2Disable"]));
            }
            set {
                this["b2Disable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool b3Disable {
            get {
                return ((bool)(this["b3Disable"]));
            }
            set {
                this["b3Disable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool b4Disable {
            get {
                return ((bool)(this["b4Disable"]));
            }
            set {
                this["b4Disable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool a1Disable {
            get {
                return ((bool)(this["a1Disable"]));
            }
            set {
                this["a1Disable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string a1ComPort {
            get {
                return ((string)(this["a1ComPort"]));
            }
            set {
                this["a1ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string a2ComPort {
            get {
                return ((string)(this["a2ComPort"]));
            }
            set {
                this["a2ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string a3ComPort {
            get {
                return ((string)(this["a3ComPort"]));
            }
            set {
                this["a3ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string a4ComPort {
            get {
                return ((string)(this["a4ComPort"]));
            }
            set {
                this["a4ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string b1ComPort {
            get {
                return ((string)(this["b1ComPort"]));
            }
            set {
                this["b1ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string b2ComPort {
            get {
                return ((string)(this["b2ComPort"]));
            }
            set {
                this["b2ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string b3ComPort {
            get {
                return ((string)(this["b3ComPort"]));
            }
            set {
                this["b3ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string b4ComPort {
            get {
                return ((string)(this["b4ComPort"]));
            }
            set {
                this["b4ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gdComPort {
            get {
                return ((string)(this["gdComPort"]));
            }
            set {
                this["gdComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double a1GlSnrOffset {
            get {
                return ((double)(this["a1GlSnrOffset"]));
            }
            set {
                this["a1GlSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double a2GlSnrOffset {
            get {
                return ((double)(this["a2GlSnrOffset"]));
            }
            set {
                this["a2GlSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double a3GlSnrOffset {
            get {
                return ((double)(this["a3GlSnrOffset"]));
            }
            set {
                this["a3GlSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double a4GlSnrOffset {
            get {
                return ((double)(this["a4GlSnrOffset"]));
            }
            set {
                this["a4GlSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double b1GlSnrOffset {
            get {
                return ((double)(this["b1GlSnrOffset"]));
            }
            set {
                this["b1GlSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double b2GlSnrOffset {
            get {
                return ((double)(this["b2GlSnrOffset"]));
            }
            set {
                this["b2GlSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double b3GlSnrOffset {
            get {
                return ((double)(this["b3GlSnrOffset"]));
            }
            set {
                this["b3GlSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double b4GlSnrOffset {
            get {
                return ((double)(this["b4GlSnrOffset"]));
            }
            set {
                this["b4GlSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double a1GpSnrOffset {
            get {
                return ((double)(this["a1GpSnrOffset"]));
            }
            set {
                this["a1GpSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double a2GpSnrOffset {
            get {
                return ((double)(this["a2GpSnrOffset"]));
            }
            set {
                this["a2GpSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double a3GpSnrOffset {
            get {
                return ((double)(this["a3GpSnrOffset"]));
            }
            set {
                this["a3GpSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double a4GpSnrOffset {
            get {
                return ((double)(this["a4GpSnrOffset"]));
            }
            set {
                this["a4GpSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double b1GpSnrOffset {
            get {
                return ((double)(this["b1GpSnrOffset"]));
            }
            set {
                this["b1GpSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double b2GpSnrOffset {
            get {
                return ((double)(this["b2GpSnrOffset"]));
            }
            set {
                this["b2GpSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double b3GpSnrOffset {
            get {
                return ((double)(this["b3GpSnrOffset"]));
            }
            set {
                this["b3GpSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double b4GpSnrOffset {
            get {
                return ((double)(this["b4GpSnrOffset"]));
            }
            set {
                this["b4GpSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double a1BdSnrOffset {
            get {
                return ((double)(this["a1BdSnrOffset"]));
            }
            set {
                this["a1BdSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double a2BdSnrOffset {
            get {
                return ((double)(this["a2BdSnrOffset"]));
            }
            set {
                this["a2BdSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double a3BdSnrOffset {
            get {
                return ((double)(this["a3BdSnrOffset"]));
            }
            set {
                this["a3BdSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double a4BdSnrOffset {
            get {
                return ((double)(this["a4BdSnrOffset"]));
            }
            set {
                this["a4BdSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double b1BdSnrOffset {
            get {
                return ((double)(this["b1BdSnrOffset"]));
            }
            set {
                this["b1BdSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double b2BdSnrOffset {
            get {
                return ((double)(this["b2BdSnrOffset"]));
            }
            set {
                this["b2BdSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double b3BdSnrOffset {
            get {
                return ((double)(this["b3BdSnrOffset"]));
            }
            set {
                this["b3BdSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double b4BdSnrOffset {
            get {
                return ((double)(this["b4BdSnrOffset"]));
            }
            set {
                this["b4BdSnrOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TesterNumber {
            get {
                return ((string)(this["TesterNumber"]));
            }
            set {
                this["TesterNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FixtureNumber {
            get {
                return ((int)(this["FixtureNumber"]));
            }
            set {
                this["FixtureNumber"] = value;
            }
        }
    }
}
